//package com.example.checklic.utils;
//
//import com.itextpdf.html2pdf.HtmlConverter;
//import java.io.File;
//import java.io.FileOutputStream;
//import java.io.IOException;
//
//public class HTMLToPDFConverter {
//
//    public static void main(String[] args) {
//        String htmlContent = "<div id=\"resultAppend\">		<div class=\"result\">\n"
//                + "			<div class=\"tableDiv\"> \n"
//                + "				<table class=\"table\">\n"
//                + "					<tbody><tr><th colspan=\"2\">LIC New Endowment (914)</th></tr>\n"
//                + "					<tr><td><strong>Basic Sum Assured</strong></td><td>1000000</td></tr>						<tr><td><strong>Age</strong></td><td>8</td></tr>	\n"
//                + "					<tr><td><strong>Policy Term</strong></td><td>12</td></tr>\n"
//                + "					<tr><td><strong>Death Sum Assured</strong></td><td>1000000</td></tr>\n"
//                + "					<tr><td><strong>Accidental Rider Sum Assured</strong></td><td>0</td></tr>\n"
//                + "					<tr><td><strong>Term Rider Sum Assured</strong></td><td>0</td></tr>\n"
//                + "				</tbody></table>\n"
//                + "			</div>\n"
//                + "			<div class=\"tableDiv\"> \n"
//                + "			<table class=\"table\">\n"
//                + "				<tbody><tr>\n"
//                + "					<th colspan=\"5\">First Year Premium</th>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Mode</strong></td><td><strong>Premium</strong></td><td><strong>GST (@4.5% )</strong></td><td><strong>Total Premium</strong></td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Yearly</strong></td><td>84661</td><td>3810</td><td>88471</td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Half Yearly</strong></td><td>42778</td><td>1925</td><td>44703</td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Quarterly</strong></td><td>21613</td><td>973</td><td>22586</td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Monthly</strong></td><td>7204</td><td>324</td><td>7528</td>\n"
//                + "				</tr>\n"
//                + "			</tbody></table>\n"
//                + "			<table class=\"table\">\n"
//                + "				<tbody><tr>\n"
//                + "					<th colspan=\"5\">Second Year Onward Premium</th>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Mode</strong></td><td><strong>Premium</strong></td><td><strong>GST (@2.25% )</strong></td><td><strong>Total Premium</strong></td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Yearly</strong></td><td>84661</td><td>1905</td><td>86566</td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Half Yearly</strong></td><td>42778</td><td>963</td><td>43741</td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Quarterly</strong></td><td>21613</td><td>486</td><td>22099</td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Monthly</strong></td><td>7204</td><td>162</td><td>7366</td>\n"
//                + "				</tr>\n"
//                + "			</tbody></table>\n"
//                + "		</div>\n"
//                + "		\n"
//                + "		<div class=\"ajdiv\">\n"
//                + "			<table class=\"table\">\n"
//                + "				<tbody><tr>\n"
//                + "					<th colspan=\"2\">Maturity Benefits</th>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Sum Assured (A)</strong></td><td>1000000</td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Total Premium Paid (Approx)</strong></td><td>1040695</td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Accumulated Bonus (Approx) (B)</strong></td><td>456000</td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Final Addition Bonus (FAB) (Approx) (C)</strong></td><td>0</td>\n"
//                + "				</tr>\n"
//                + "				<tr>\n"
//                + "					<td><strong>Maturity (Approx) (A+B+C)</strong></td><td><strong>1456000</strong></td>\n"
//                + "				</tr>\n"
//                + "			</tbody></table>\n"
//                + "		</div>\n"
//                + "		<ul><li>Accidental and Disability Benefit Rider is not available for less than 18 years.</li></ul>\n"
//                + "		</div><style> \n"
//                + ".table {\n"
//                + "                width: 100%;\n"
//                + "                border-collapse: collapse;\n"
//                + "                margin-bottom: 20px;\n"
//                + "                text-align: center;\n"
//                + "                margin: 0 auto;\n"
//                + "            }\n"
//                + "\n"
//                + "            .table th,\n"
//                + "            .table td {\n"
//                + "                border: 1px solid #ddd;\n"
//                + "                padding: 8px;\n"
//                + "            }\n"
//                + "\n"
//                + "            .table th {\n"
//                + "                background-color: #333;\n"
//                + "                color: #fff;\n"
//                + "            }\n"
//                + "\n"
//                + "            .table tr:nth-child(even) {\n"
//                + "                background-color: #f2f2f2;\n"
//                + "            }\n"
//                + "\n"
//                + "            .table tr:hover {\n"
//                + "                background-color: #ddd;\n"
//                + "            }\n"
//                + "</style>\n"
//                + "\n"
//                + "</div>";
//
//        String outputPdfFile = "output.pdf";
//        File pdfFile = new File(outputPdfFile);
//        try (FileOutputStream outputStream = new FileOutputStream(pdfFile)) {
//            HtmlConverter.convertToPdf(htmlContent, outputStream);
//            System.out.println("PDF generated successfully at: " + pdfFile.getAbsolutePath());
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//    }
//}
